/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Adminpackage;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author zikrea
 */
public class Ajoutprix extends javax.swing.JFrame {

    private AdminPage adminPage;
    private final Connection connection = AdminLogin.Connect();

    /**
     * Creates new form AjoutPeintInfo
     */
    public Ajoutprix() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public Ajoutprix(AdminPage adminPage) {
        this.adminPage = adminPage;
        initComponents();
        setLocationRelativeTo(null);
    }

    ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comp = new javax.swing.JPanel();
        champ_input = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajout du prix d'un m²");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        comp.setBackground(new java.awt.Color(0, 153, 153));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout compLayout = new javax.swing.GroupLayout(comp);
        comp.setLayout(compLayout);
        compLayout.setHorizontalGroup(
            compLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(champ_input, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, compLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(122, 122, 122))
        );
        compLayout.setVerticalGroup(
            compLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(champ_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    public void reinitialiser() {
        champ_input.setText("");
    }

    private void insertPrixmc() throws SQLException {
        String sql = "INSERT INTO Prixmc (Prixmc) VALUES (?)";

        String textInput = champ_input.getText().trim();
        if (textInput.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Veuillez entrer une valeur valide.", "Erreur", JOptionPane.ERROR_MESSAGE);
            return; 
        }

        try {

            try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
                int input = Integer.parseInt(champ_input.getText());

                preparedStatement.setInt(1, input);

                int rowsAffected = preparedStatement.executeUpdate();
                if (rowsAffected > 0 && !"".equals(input)) {
                    if (this.adminPage != null) {
                        this.adminPage.setChampPrixValue(champ_input.getText());
                        reinitialiser();
                        JOptionPane.showMessageDialog(null, "Prix ajouté avec succès.", "Information", JOptionPane.INFORMATION_MESSAGE);
                        System.out.println("Data insérée");
                        close();

                    }

                } else {
                    System.out.println("L'insertion a échoué.");
                    JOptionPane.showMessageDialog(null, "Veuillez bien vérifier les champs", "Erreur", JOptionPane.ERROR_MESSAGE);
                }

            }
        } catch (SQLException e) {
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            insertPrixmc();
        } catch (SQLException ex) {
            Logger.getLogger(Ajoutprix.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajoutprix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajoutprix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajoutprix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajoutprix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajoutprix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField champ_input;
    private javax.swing.JPanel comp;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
